# File: docker-compose.yml
# This file is used to define and run multi-container Docker applications.
# It specifies the services, networks, and volumes required for the application.
services:
  db:
    image: postgres:13
    container_name: formalink
    environment:
      POSTGRES_USER: suji # ← Change this to your desired project username
      POSTGRES_PASSWORD: suji # ← Change this to your desired project password
      POSTGRES_DB: formalink_db # ← Change this to your desired project database name
    ports:
      - "5432:5432"    # ← HostPort:ContainerPort  
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - fastapi_network
networks:
  fastapi_network:
    driver: bridge
