"""Test

Revision ID: 203afe449dac
Revises: 9f6cbf16efdc
Create Date: 2025-06-02 17:07:44.927494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '203afe449dac'
down_revision: Union[str, None] = '9f6cbf16efdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashedPassword', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('admin_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_admin_user_admin_user_id'), 'admin_user', ['admin_user_id'], unique=False)
    op.create_table('forms',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('form_name', sa.String(), nullable=False),
    sa.Column('form_description', sa.String(), nullable=False),
    sa.Column('form_type', sa.String(), nullable=False),
    sa.Column('form_created_at', sa.DateTime(), nullable=False),
    sa.Column('form_updated_at', sa.DateTime(), nullable=False),
    sa.Column('form_created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['form_created_by'], ['admin_user.admin_user_id'], ),
    sa.PrimaryKeyConstraint('form_id'),
    sa.UniqueConstraint('form_name')
    )
    op.create_index(op.f('ix_forms_form_id'), 'forms', ['form_id'], unique=False)
    op.create_table('responses',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('submited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index(op.f('ix_responses_response_id'), 'responses', ['response_id'], unique=False)
    op.create_table('sections',
    sa.Column('section_uuid', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('section_description', sa.String(), nullable=True),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], ),
    sa.PrimaryKeyConstraint('section_uuid')
    )
    op.create_index(op.f('ix_sections_section_id'), 'sections', ['section_id'], unique=False)
    op.create_index(op.f('ix_sections_section_uuid'), 'sections', ['section_uuid'], unique=False)
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('section_uuid', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_type', sa.Enum('RADIO', 'MULTIPLE_GRID', 'SCALE', 'CHECKBOX', 'DROPDOWN', 'SHORT_TEXT', 'PARAGRAPH', 'NUMBER', 'DATE', 'TIME', 'FILE_UPLOAD', 'EMAIL', 'PHONE', 'URL', 'CURRENCY', 'ADDRESS', 'SIGNATURE', 'MATRIX', 'MATRIX_RANKING', 'TIMEZONE', 'FILE', 'PHONE_NUMBER', 'TIME_RANGE', name='questiontype'), nullable=False),
    sa.Column('is_required', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_uuid'], ['sections.section_uuid'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=False)
    op.create_table('answers',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['responses.response_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_answers_answer_id'), 'answers', ['answer_id'], unique=False)
    op.create_table('logic',
    sa.Column('logic_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('source_question_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('target_question_id', sa.Integer(), nullable=True),
    sa.Column('target_section_uuid', sa.UUID(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], ),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['target_question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['target_section_uuid'], ['sections.section_uuid'], ),
    sa.PrimaryKeyConstraint('logic_id')
    )
    op.create_index(op.f('ix_logic_logic_id'), 'logic', ['logic_id'], unique=False)
    op.create_table('options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(), nullable=False),
    sa.Column('option_type', sa.Enum('RADIO', 'MULTIPLE_GRID', 'SCALE', 'CHECKBOX', 'DROPDOWN', name='optiontype'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_index(op.f('ix_options_option_id'), 'options', ['option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_options_option_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_logic_logic_id'), table_name='logic')
    op.drop_table('logic')
    op.drop_index(op.f('ix_answers_answer_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_sections_section_uuid'), table_name='sections')
    op.drop_index(op.f('ix_sections_section_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_responses_response_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_forms_form_id'), table_name='forms')
    op.drop_table('forms')
    op.drop_index(op.f('ix_admin_user_admin_user_id'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
