"""Initial commit

Revision ID: 58c4dceb8640
Revises: 90fe4cff604e
Create Date: 2025-05-15 16:47:30.528024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c4dceb8640'
down_revision: Union[str, None] = '90fe4cff604e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('hashedPassword', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('admin_user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phoneNumber')
    )
    op.create_index(op.f('ix_admin_user_admin_user_id'), 'admin_user', ['admin_user_id'], unique=False)
    op.create_table('forms',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('form_name', sa.String(), nullable=False),
    sa.Column('form_description', sa.String(), nullable=False),
    sa.Column('form_type', sa.String(), nullable=False),
    sa.Column('form_created_at', sa.DateTime(), nullable=False),
    sa.Column('form_updated_at', sa.DateTime(), nullable=False),
    sa.Column('form_created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['form_created_by'], ['admin_user.admin_user_id'], ),
    sa.PrimaryKeyConstraint('form_id'),
    sa.UniqueConstraint('form_name')
    )
    op.create_index(op.f('ix_forms_form_id'), 'forms', ['form_id'], unique=False)
    op.create_table('responses',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('submited_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index(op.f('ix_responses_response_id'), 'responses', ['response_id'], unique=False)
    op.create_table('sections',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('section_description', sa.String(), nullable=True),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_sections_section_id'), 'sections', ['section_id'], unique=False)
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('question_type', sa.Enum('SHORT_TEXT', 'PARAGRAPH', 'NUMBER', 'RADIO', 'MULTIPLE_GRID', 'SCALE', 'CHECKBOX', 'DROPDOWN', 'DATE', 'TIME', 'FILE_UPLOAD', 'EMAIL', 'PHONE', 'URL', 'CURRENCY', 'ADDRESS', 'SIGNATURE', 'MATRIX', 'MATRIX_RANKING', 'TIMEZONE', 'FILE', 'PHONE_NUMBER', 'TIME_RANGE', name='questiontype'), nullable=False),
    sa.Column('is_required', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=False)
    op.create_table('answers',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['responses.response_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_answers_answer_id'), 'answers', ['answer_id'], unique=False)
    op.create_table('logic',
    sa.Column('logic_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('source_question_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('target_question_id', sa.Integer(), nullable=True),
    sa.Column('target_section_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.form_id'], ),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['target_question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['target_section_id'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('logic_id')
    )
    op.create_index(op.f('ix_logic_logic_id'), 'logic', ['logic_id'], unique=False)
    op.create_table('options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_index(op.f('ix_options_option_id'), 'options', ['option_id'], unique=False)
    op.drop_index('ix_purchases_id', table_name='purchases')
    op.drop_index('ix_purchases_product_id', table_name='purchases')
    op.drop_index('ix_purchases_user_id', table_name='purchases')
    op.drop_table('purchases')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_products_id', table_name='products')
    op.drop_index('ix_products_prod_name', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('prod_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prod_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_products_prod_name', 'products', ['prod_name'], unique=True)
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('purchases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='purchases_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='purchases_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchases_pkey')
    )
    op.create_index('ix_purchases_user_id', 'purchases', ['user_id'], unique=False)
    op.create_index('ix_purchases_product_id', 'purchases', ['product_id'], unique=False)
    op.create_index('ix_purchases_id', 'purchases', ['id'], unique=False)
    op.drop_index(op.f('ix_options_option_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_logic_logic_id'), table_name='logic')
    op.drop_table('logic')
    op.drop_index(op.f('ix_answers_answer_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_sections_section_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_responses_response_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_forms_form_id'), table_name='forms')
    op.drop_table('forms')
    op.drop_index(op.f('ix_admin_user_admin_user_id'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
