"""Test

Revision ID: 99efb9e96447
Revises: 203afe449dac
Create Date: 2025-06-04 11:49:41.091164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99efb9e96447'
down_revision: Union[str, None] = '203afe449dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_column('admin_user', 'hashedPassword')
    op.add_column('questions', sa.Column('form_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'questions', 'forms', ['form_id'], ['form_id'])
    op.add_column('responses', sa.Column('question_id', sa.Integer(), nullable=False))
    op.add_column('responses', sa.Column('answer_text', sa.String(), nullable=False))
    op.create_foreign_key(None, 'responses', 'questions', ['question_id'], ['question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_column('responses', 'answer_text')
    op.drop_column('responses', 'question_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'form_id')
    op.add_column('admin_user', sa.Column('hashedPassword', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('admin_user', 'hashed_password')
    # ### end Alembic commands ###
