"""Modified ENUMS

Revision ID: 9f6cbf16efdc
Revises: d153fe3d5ae7
Create Date: 2025-05-16 11:04:06.891257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f6cbf16efdc'
down_revision: Union[str, None] = 'd153fe3d5ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('answer_text', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('options', sa.Column('option_type', sa.Enum('RADIO', 'MULTIPLE_GRID', 'SCALE', 'CHECKBOX', 'DROPDOWN', name='optiontype'), nullable=False))
    op.add_column('options', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'order')
    op.drop_column('options', 'option_type')
    op.drop_column('answers', 'answer_text')
    # ### end Alembic commands ###
